version: "3"

services:
  elastic:
    image: elasticsearch:7.5.1
    environment:
      - discovery.type=single-node
      - TZ=Asia/Shanghai
    ports:
      - "9200:9200"
  kibana:
    image: kibana:7.5.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
      - TZ=Asia/Shanghai
    ports:
      - "5601:5601"
    links:
      - elastic
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - ./test.env
    volumes:
      - ..:/workspace
    command: sleep infinity
    links:
      - elastic
