version: "3"

services:
  # elastic:
  #   image: elasticsearch:7.5.1
  #   environment:
  #     - discovery.type=single-node
  #     - TZ=Asia/Shanghai
  #   ports:
  #     - "9200:9200"
  # kibana:
  #   image: kibana:7.5.1
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elastic:9200
  #     - TZ=Asia/Shanghai
  #   ports:
  #     - "5601:5601"
  #   links:
  #     - elastic
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    links:
      - loki
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - ./test.env
    volumes:
      - ..:/workspace
      - vscode-extensions:/root/.vscode-server/extensions
    command: sleep infinity
    links:
      # - elastic
      - loki

volumes:
  vscode-extensions:
    external: true