name: Build filebeat-oracle
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x']
    services:
      elasticsearch:
        image: elasticsearch:7.5.1
        env:
          discovery.type: single-node
        ports:
        - 9200
        options: --health-cmd="curl http://127.0.0.1:9200" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      # - name: Test filebeat-oracle
      #   run: python filebeat_oracle_test.py
      - name: Post Test Log To Elasticsearch
        run: |
          esport=${{ job.services.elasticsearch.ports['9200'] }}
          python filebeat_oracle.py --oracleVersion 10 --alertFilePath "./test/10.log" --elasticHost 127.0.0.1 --elasticPort $esport --elasticIndex filebeat-oracle
        env:
          oracle_version: 10
      - name: Test Elasticsearch Index Document Number
        run: |
          esport=${{ job.services.elasticsearch.ports['9200'] }}
          for i in `seq 1 60`
          do
            cnt=$(curl -s -XPOST -H"Content-Type: application/json" http://127.0.0.1:${esport}/_sql?format=txt -d '{"query": "select count(*) from \"filebeat-oracle-*\" WHERE \"oracle.version\" = 10 "}' | tail -n 1)
            cnt=$(echo -e "${cnt}" | tr -d '[:space:]')
            [[ "${cnt}" == "10" ]] && echo "document count: ${cnt}. Test Document Number Success." && exit 0
            echo "document count: ${cnt}. retry: ${i}."
            sleep 1
          done
          exit 1
      - run: pip install wheel
      - run: python setup.py bdist_wheel
      - name: Publish package
        if: github.event_name == 'push'
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.pypi_username }}
          password: ${{ secrets.pypi_password }}
